/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lilol
 */
public class AthleticRaceInterface extends javax.swing.JFrame {

    /**
     * Creates new form AthleticRaceInterface
     */
    public AthleticRaceInterface() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegistrarCorredor = new javax.swing.JLabel();
        txtRegistrarCorredor = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        lblCorredoresRegistrador = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCorredores = new javax.swing.JTextArea();
        lblResultados = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultados = new javax.swing.JTextArea();
        btnIniciar = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        btnTerminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRegistrarCorredor.setText("Registrar Corredor");

        txtRegistrarCorredor.setText("Ingresa Nombre");
        txtRegistrarCorredor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRegistrarCorredorMouseClicked(evt);
            }
        });
        txtRegistrarCorredor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRegistrarCorredorKeyPressed(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        lblCorredoresRegistrador.setText("Corredores Registrados");

        txtCorredores.setEditable(false);
        txtCorredores.setColumns(20);
        txtCorredores.setRows(5);
        jScrollPane1.setViewportView(txtCorredores);

        lblResultados.setText("Resultados");

        txtResultados.setEditable(false);
        txtResultados.setColumns(20);
        txtResultados.setRows(5);
        jScrollPane2.setViewportView(txtResultados);

        btnIniciar.setText("Iniciar");
        btnIniciar.setEnabled(false);
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.setEnabled(false);
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        btnTerminar.setText("Terminar");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnIniciar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnTerminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblRegistrarCorredor)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtRegistrarCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCorredoresRegistrador)
                            .addComponent(lblResultados))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegistrarCorredor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRegistrarCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar))
                .addGap(18, 18, 18)
                .addComponent(lblCorredoresRegistrador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblResultados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReiniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTerminar)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRegistrarCorredorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRegistrarCorredorMouseClicked
        txtRegistrarCorredor.setText("");
    }//GEN-LAST:event_txtRegistrarCorredorMouseClicked

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (valido()&&!txtRegistrarCorredor.getText().equalsIgnoreCase("Ingresa Nombre")) {
            corredores[corredor++] = new Runner(txtRegistrarCorredor.getText());
            javax.swing.JOptionPane.showMessageDialog(this, "Registro de " + corredores[corredor - 1].getName() + " Aprobado, eres el corredor numero: " + (corredor));
            txtCorredores.setText(txtCorredores.getText() + corredor + " - " + corredores[corredor - 1].getName() + "\n");
            if (txtCorredores.getText().split("\n").length == 5) {
                btnIniciar.setEnabled(true);
                javax.swing.JOptionPane.showMessageDialog(this, "Maximo numero de corredores registrados se cierra la competencia");
                btnRegistrar.setEnabled(false);
                txtRegistrarCorredor.setEnabled(false);
                btnReiniciar.setEnabled(true);
            }
            txtRegistrarCorredor.setText("Ingresa Nombre");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        try {
            if (estaCompleto() && corriendo) {
                txtResultados.setText("");
                for (int i = 0; i < 5; i++) {
                    ThreadRunner a = new ThreadRunner(corredores[i], txtResultados);
                    a.start();
                    corriendo = false;
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "espera que la carrera termine...");
            }
        } catch (java.lang.NullPointerException e) {

        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        if (estaCompleto() && corriendo) {
            txtCorredores.setText("");
            txtResultados.setText("");
            btnRegistrar.setEnabled(true);
            btnIniciar.setEnabled(false);
            btnReiniciar.setEnabled(false);
            txtRegistrarCorredor.setEnabled(true);
            corredor=0;
        }
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        if(javax.swing.JOptionPane.showConfirmDialog(this, "Seguro que desea cerrar?")==0){
            javax.swing.JOptionPane.showMessageDialog(this, "Adios");
            System.exit(0);
        }
    }//GEN-LAST:event_btnTerminarActionPerformed

    private void txtRegistrarCorredorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRegistrarCorredorKeyPressed
        if(txtRegistrarCorredor.getText().equalsIgnoreCase("Ingresa Nombre")){
            txtRegistrarCorredor.setText("");
        }
    }//GEN-LAST:event_txtRegistrarCorredorKeyPressed

    private boolean estaCompleto() {
        if (txtResultados.getText().split("\n").length < 4) {
            return true;
        } else if (txtResultados.getText().split("\n").length == 5) {
            corriendo = true;
            return true;
        }
        return false;
    }

    private boolean valido() {
        return txtRegistrarCorredor.getText().length() > 0 && corredor < 5;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AthleticRaceInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AthleticRaceInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AthleticRaceInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AthleticRaceInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AthleticRaceInterface().setVisible(true);
            }
        });
    }

    private Runner[] corredores = new Runner[5];
    private int corredor = 0;
    private boolean corriendo = true;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCorredoresRegistrador;
    private javax.swing.JLabel lblRegistrarCorredor;
    private javax.swing.JLabel lblResultados;
    private javax.swing.JTextArea txtCorredores;
    private javax.swing.JTextField txtRegistrarCorredor;
    private javax.swing.JTextArea txtResultados;
    // End of variables declaration//GEN-END:variables
}
